'use client';

import React, { useMemo, useState } from 'react';
import Link from 'next/link';
import { ArrowLeft, BookOpen, CreditCard, FileSearch, Search, Shield, Users } from 'lucide-react';

const ARTICLES = [
  { id: 'first-client', category: 'Getting started', title: 'Add and onboard your first client', summary: 'Create a client record and prepare it for report import.', icon: Users, steps: ['Open Clients and choose Add client.', 'Enter the client’s contact details and service status.', 'Save the record before importing a report so every document stays tied to the correct client.', 'Use the next-action fields to keep follow-ups visible on the dashboard.'] },
  { id: 'import-report', category: 'Credit workflow', title: 'Import and review a credit report', summary: 'Turn a supported credit report into reviewable negative items.', icon: FileSearch, steps: ['Open Import Report and select the correct client.', 'Upload the report and wait for parsing to finish.', 'Review the parser confidence and every extracted account.', 'Correct any item before saving it to the client workspace.', 'Only saved negative items appear in Credit Audit and dispute workflows.'] },
  { id: 'credit-audit', category: 'Credit workflow', title: 'Run a client credit audit', summary: 'Create an audit from the client’s saved negative items.', icon: Shield, steps: ['Open Credit Audit and choose a client.', 'Select Run audit.', 'Review bureau totals, item categories, balances, and suggested priorities.', 'Confirm the source report before using an audit to prepare a dispute.', 'The audit never invents items; an empty report produces an empty audit.'] },
  { id: 'business-billing', category: 'Billing', title: 'Manage your FixMy.Money subscription', summary: 'Update the payment method your business uses to pay FixMy.Money.', icon: CreditCard, steps: ['Open Billing from the sidebar.', 'In Your FixMy.Money subscription, choose Manage my subscription.', 'Use the secure Stripe portal to update your card, view invoices, change plans, or cancel.', 'Return to FixMy.Money when finished.'] },
  { id: 'client-billing', category: 'Billing', title: 'Track billing for your clients', summary: 'Keep client payment status separate from your software subscription.', icon: CreditCard, steps: ['Open Billing and scroll to Client billing tracker.', 'Each row comes from a real client in your workspace.', 'Update a client’s status from the client management workflow.', 'Paid, overdue, and pending totals update from those records.'] },
  { id: 'workspace-security', category: 'Security', title: 'How business workspaces stay private', summary: 'Understand account ownership and tenant isolation.', icon: Shield, steps: ['Every business owner signs in with a unique verified email and password.', 'Onboarding creates a business workspace owned by that account.', 'Client, report, dispute, and billing queries are restricted to the signed-in owner.', 'Never share account credentials; add separate staff access only through approved team features.'] },
];

export default function KnowledgeBaseContent() {
  const [search, setSearch] = useState('');
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const filtered = useMemo(() => ARTICLES.filter(a => `${a.title} ${a.summary} ${a.category}`.toLowerCase().includes(search.toLowerCase())), [search]);
  const selected = ARTICLES.find(a => a.id === selectedId);

  if (selected) {
    const Icon = selected.icon;
    return <div className="p-4 sm:p-6 max-w-3xl mx-auto"><button onClick={() => setSelectedId(null)} className="inline-flex items-center gap-2 text-sm font-bold text-blue-600 hover:underline"><ArrowLeft size={15}/>Back to all guides</button><article className="mt-5 rounded-2xl border border-slate-200 bg-white p-6 sm:p-8"><div className="w-11 h-11 rounded-xl bg-blue-50 text-blue-600 flex items-center justify-center"><Icon size={21}/></div><p className="text-xs font-bold uppercase tracking-wider text-blue-600 mt-5">{selected.category}</p><h1 className="text-2xl font-bold text-slate-900 mt-2">{selected.title}</h1><p className="text-slate-500 mt-2">{selected.summary}</p><ol className="mt-7 space-y-4">{selected.steps.map((step, index) => <li key={step} className="flex gap-4"><span className="w-7 h-7 rounded-full bg-slate-900 text-white flex items-center justify-center text-xs font-bold shrink-0">{index + 1}</span><p className="text-sm text-slate-700 pt-1">{step}</p></li>)}</ol></article></div>;
  }

  return <div className="p-4 sm:p-6 max-w-6xl mx-auto space-y-6"><div><div className="w-11 h-11 rounded-xl bg-blue-50 text-blue-600 flex items-center justify-center"><BookOpen size={22}/></div><h1 className="text-2xl font-bold text-slate-900 mt-4">Knowledge base</h1><p className="text-sm text-slate-500 mt-1">Working guides for the FixMy.Money business platform.</p></div><div className="relative"><Search className="absolute left-4 top-1/2 -translate-y-1/2 text-slate-400" size={18}/><input value={search} onChange={e => setSearch(e.target.value)} placeholder="Search setup, credit audits, billing, or security…" className="w-full rounded-xl border border-slate-200 bg-white pl-11 pr-4 py-3 text-sm outline-none focus:ring-2 focus:ring-blue-200"/></div><div className="grid md:grid-cols-2 gap-4">{filtered.map(article => { const Icon = article.icon; return <button key={article.id} onClick={() => setSelectedId(article.id)} className="text-left rounded-2xl border border-slate-200 bg-white p-5 hover:border-blue-300 hover:shadow-sm transition-all"><div className="flex gap-4"><div className="w-10 h-10 rounded-xl bg-slate-50 text-blue-600 flex items-center justify-center shrink-0"><Icon size={19}/></div><div><p className="text-xs font-bold uppercase tracking-wider text-slate-400">{article.category}</p><h2 className="font-bold text-slate-900 mt-1">{article.title}</h2><p className="text-sm text-slate-500 mt-2">{article.summary}</p><span className="inline-block text-sm font-bold text-blue-600 mt-3">Read guide →</span></div></div></button>; })}</div>{filtered.length === 0 && <div className="rounded-xl border border-dashed border-slate-300 p-10 text-center text-sm text-slate-500">No guides match that search.</div>}<div className="rounded-2xl bg-slate-900 p-6 text-white flex items-center justify-between gap-4 flex-wrap"><div><p className="font-bold">Need help with your workspace?</p><p className="text-sm text-slate-300 mt-1">Open support chat from inside your secure account.</p></div><Link href="/live-chat" className="rounded-lg bg-white px-4 py-2 text-sm font-bold text-slate-900">Contact support</Link></div></div>;
}
