'use client';

import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { ArrowRight, Check, FileCheck2, FileSearch, MoveRight, ShieldCheck } from 'lucide-react';
import type { ComparisonPage } from '@/lib/comparisons/pages';
import MarketingWorkspacePreview from '@/components/MarketingWorkspacePreview';

export default function ComparisonLandingPage({ page }: { page: ComparisonPage }) {
  const router = useRouter();
  const start = () => router.push('/signup?plan=professional');
  return <div className="min-h-screen bg-white text-[#111827]">
    <nav className="sticky top-3 z-50 px-4"><div className="mx-auto flex h-[68px] max-w-6xl items-center justify-between rounded-2xl border border-slate-200 bg-white/90 px-5 shadow-lg backdrop-blur-xl"><Link href="/" className="text-lg font-black tracking-tight">FixMy<span className="text-blue-600">.</span>Money</Link><div className="flex items-center gap-5"><Link href="/pricing" className="hidden text-sm font-semibold sm:block">Pricing</Link><button onClick={start} className="rounded-xl bg-gradient-to-r from-blue-600 to-violet-600 px-5 py-3 text-sm font-bold text-white">Start $1 Trial</button></div></div></nav>
    <section className="relative overflow-hidden px-5 pb-20 pt-20"><div className="absolute left-0 top-0 h-80 w-80 rounded-full bg-cyan-300/20 blur-3xl"/><div className="absolute right-0 top-0 h-96 w-96 rounded-full bg-violet-300/20 blur-3xl"/><div className="relative mx-auto grid max-w-6xl items-center gap-14 lg:grid-cols-[.9fr_1.1fr]"><div><p className="text-xs font-black uppercase tracking-[.22em] text-blue-600">{page.eyebrow}</p><h1 className="mt-6 text-balance text-5xl font-black leading-[1.03] tracking-[-.05em] sm:text-6xl">{page.title}</h1><p className="mt-6 max-w-xl text-lg leading-8 text-slate-500">{page.description}</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><button onClick={start} className="rounded-xl bg-gradient-to-r from-blue-600 to-violet-600 px-7 py-4 font-bold text-white shadow-xl shadow-blue-600/20">Try FixMy.Money</button><Link href="/demo" className="rounded-xl border border-slate-200 bg-white px-7 py-4 text-center font-bold shadow-sm">View Product Demo</Link></div></div><MarketingWorkspacePreview compact/></div></section>
    <section className="border-y border-slate-200 bg-[#F7F9FC] px-5 py-24"><div className="mx-auto grid max-w-6xl gap-12 lg:grid-cols-2"><div><p className="text-xs font-black uppercase tracking-[.2em] text-blue-600">Who it suits</p><h2 className="mt-5 text-4xl font-black tracking-[-.04em]">Start with operating fit.</h2><p className="mt-6 text-lg leading-8 text-slate-500">{page.suitedFor}</p></div><div className="rounded-3xl bg-gradient-to-br from-[#0B1220] to-[#172554] p-8 text-white shadow-2xl"><p className="text-xs font-black uppercase tracking-[.2em] text-cyan-400">Verified pricing</p><p className="mt-5 text-lg leading-8 text-white/75">{page.pricing}</p>{page.source&&<a href={page.source} target="_blank" rel="noreferrer" className="mt-6 inline-flex items-center gap-2 font-bold text-cyan-400">{page.sourceLabel}<ArrowRight size={16}/></a>}</div></div></section>
    <section className="px-5 py-24"><div className="mx-auto max-w-6xl"><p className="text-xs font-black uppercase tracking-[.2em] text-violet-600">Where FixMy.Money differs</p><h2 className="mt-5 max-w-3xl text-4xl font-black tracking-[-.04em] sm:text-5xl">Compare the workflow, not just the inventory.</h2><div className="mt-12 grid gap-4 md:grid-cols-3">{page.differences.map((item,i)=><article key={item} className={`rounded-3xl border border-slate-200 p-7 ${i===1?'bg-gradient-to-br from-blue-600 to-violet-600 text-white shadow-xl':'bg-white shadow-sm'}`}><Check className={i===1?'text-cyan-300':'text-blue-600'}/><p className={`mt-8 leading-7 ${i===1?'text-white/80':'text-slate-600'}`}>{item}</p></article>)}</div><div className="mt-12 overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-xl"><div className="grid grid-cols-[.8fr_1fr_1fr] bg-slate-50 px-5 py-4 text-sm font-black"><span>Capability</span><span className="text-blue-600">FixMy.Money</span><span>{page.competitor||'What to verify'}</span></div>{[['Report analysis','Documented','Confirm on selected plan'],['Source-linked evidence','Documented','Not publicly documented unless vendor states it'],['Named human approval','Documented','Not publicly documented unless vendor states it'],['Client management','Documented','Confirm limits and plan'],['Billing workflow','Stripe-powered','Confirm processor and plan']].map(row=><div key={row[0]} className="grid grid-cols-[.8fr_1fr_1fr] border-t border-slate-200 px-5 py-4 text-sm"><b>{row[0]}</b><span>{row[1]}</span><span className="text-slate-500">{row[2]}</span></div>)}</div></div></section>
    <section className="bg-[#0B1220] px-5 py-24 text-white"><div className="mx-auto grid max-w-6xl gap-14 lg:grid-cols-[.8fr_1.2fr]"><div><p className="text-xs font-black uppercase tracking-[.2em] text-cyan-400">Migration plan</p><h2 className="mt-5 text-4xl font-black tracking-[-.04em]">Switch without losing context.</h2><p className="mt-6 leading-7 text-white/60">We help preserve the records your team needs to keep serving clients while the new workflow comes online.</p></div><ol className="space-y-4">{page.migration.map((item,i)=><li key={item} className="flex gap-5 rounded-2xl border border-white/10 bg-white/5 p-5"><span className="font-black text-cyan-400">0{i+1}</span><span className="text-white/75">{item}</span></li>)}</ol></div></section>
    <section className="px-5 py-24"><div className="mx-auto max-w-5xl rounded-[32px] bg-gradient-to-br from-blue-600 to-violet-700 px-7 py-16 text-center text-white shadow-2xl shadow-blue-600/20"><MoveRight className="mx-auto"/><h2 className="mx-auto mt-6 max-w-3xl text-4xl font-black tracking-[-.04em]">See whether evidence-first fits your agency.</h2><p className="mx-auto mt-5 max-w-2xl text-white/80">Try the core workflow for $1, or walk through a migration with our team.</p><div className="mt-8 flex flex-col justify-center gap-3 sm:flex-row"><button onClick={start} className="rounded-xl bg-[#0B1220] px-7 py-4 font-bold">Start $1 Trial</button><Link href="/switch" className="rounded-xl bg-white px-7 py-4 font-bold text-[#111827]">Plan my migration</Link></div></div></section>
  </div>;
}
