import { Activity, BarChart3, Check, ChevronRight, CircleAlert, FileSearch, Gauge, Sparkles, UserRound } from 'lucide-react';

export default function MarketingWorkspacePreview({ compact = false }: { compact?: boolean }) {
  return <div className="relative isolate">
    <div className="absolute -inset-8 -z-10 rounded-full bg-gradient-to-br from-blue-400/25 via-violet-400/20 to-cyan-300/20 blur-3xl" />
    <div className="overflow-hidden rounded-[24px] border border-slate-200 bg-white shadow-[0_32px_80px_-24px_rgba(37,99,235,.28)]">
      <div className="flex h-12 items-center gap-2 border-b border-slate-200 px-4"><span className="h-2.5 w-2.5 rounded-full bg-red-400"/><span className="h-2.5 w-2.5 rounded-full bg-amber-400"/><span className="h-2.5 w-2.5 rounded-full bg-emerald-400"/><span className="ml-3 text-[11px] font-semibold text-slate-400">Evidence workspace · Jordan Ellis</span></div>
      <div className={`grid ${compact ? '' : 'lg:grid-cols-[150px_1fr]'}`}>
        {!compact && <aside className="hidden bg-[#0B1220] p-4 text-white lg:block"><div className="mb-7 flex items-center gap-2 text-xs font-extrabold"><span className="grid h-7 w-7 place-items-center rounded-lg bg-blue-600">F</span> FixMy.Money</div>{['Overview','Report analysis','Evidence review','Dispute rounds','Outcomes'].map((x,i)=><div key={x} className={`mb-1.5 rounded-lg px-2.5 py-2 text-[10px] font-semibold ${i===2?'bg-blue-600':'text-slate-400'}`}>{x}</div>)}</aside>}
        <div className="bg-[#F7F9FC] p-4 sm:p-5">
          <div className="flex items-start justify-between gap-4"><div className="flex gap-3"><span className="grid h-10 w-10 place-items-center rounded-full bg-gradient-to-br from-blue-500 to-violet-600 text-xs font-black text-white">JE</span><div><p className="text-sm font-extrabold text-slate-900">Jordan Ellis</p><p className="text-[10px] text-slate-500">Round 1 · Evidence review</p></div></div><span className="rounded-full bg-emerald-50 px-2.5 py-1 text-[9px] font-bold text-emerald-700">Human review active</span></div>
          <div className="mt-4 grid grid-cols-3 gap-2">{[['TU','641','+18'],['EX','628','+11'],['EQ','654','+23']].map(([b,s,d])=><div key={b} className="rounded-xl border border-slate-200 bg-white p-2.5"><div className="flex items-center justify-between"><span className="text-[9px] font-black text-slate-400">{b}</span><span className="text-[8px] font-bold text-emerald-600">{d}</span></div><p className="mt-1 text-lg font-black text-slate-900">{s}</p></div>)}</div>
          <div className="mt-3 grid gap-3 md:grid-cols-[1fr_1.15fr]">
            <div className="overflow-hidden rounded-xl border border-slate-200 bg-white"><div className="border-b border-slate-100 px-3 py-2 text-[10px] font-extrabold text-slate-700">Imported accounts <span className="float-right text-blue-600">7 flagged</span></div>{[['Northstar Bank','Balance mismatch','High'],['Metro Collection','Date inconsistency','Review'],['Lumen Card','Payment history','High']].map((r,i)=><div key={r[0]} className={`border-b border-slate-100 px-3 py-2.5 last:border-0 ${i===0?'bg-blue-50':''}`}><div className="flex items-center justify-between"><span className="text-[10px] font-bold text-slate-800">{r[0]}</span><ChevronRight size={12} className="text-slate-400"/></div><div className="mt-1 flex justify-between text-[8px]"><span className="text-slate-500">{r[1]}</span><span className={i===1?'text-amber-600':'text-emerald-600'}>{r[2]}</span></div></div>)}</div>
            <div className="rounded-xl border border-slate-200 bg-white p-3"><div className="flex items-center gap-2 text-[10px] font-extrabold text-violet-700"><Sparkles size={13}/> AI inconsistency analysis</div><p className="mt-2 text-[10px] font-bold leading-4 text-slate-800">Possible balance and status inconsistency across two bureaus.</p><div className="mt-3 grid grid-cols-[1fr_auto] items-center gap-2 rounded-lg bg-violet-50 p-2.5"><div><p className="text-[8px] font-bold uppercase tracking-wide text-violet-600">Estimated removal potential</p><p className="mt-1 text-[8px] text-slate-500">Weighted from evidence, inconsistency type, and report data</p></div><span className="text-xl font-black text-violet-700">78</span></div><div className="mt-3 flex items-center justify-between"><span className="text-[9px] font-semibold text-slate-500">Evidence completeness</span><span className="text-[9px] font-black text-emerald-600">92%</span></div><div className="mt-1 h-1.5 overflow-hidden rounded-full bg-slate-100"><div className="h-full w-[92%] rounded-full bg-gradient-to-r from-cyan-500 to-blue-600"/></div><div className="mt-3 flex gap-1.5"><button className="rounded-md bg-blue-600 px-2.5 py-1.5 text-[8px] font-bold text-white">Approve</button><button className="rounded-md border border-slate-200 px-2.5 py-1.5 text-[8px] font-bold">Edit</button><button className="rounded-md border border-slate-200 px-2.5 py-1.5 text-[8px] font-bold">Exclude</button></div></div>
          </div>
          <div className="mt-3 flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-3 py-2.5"><Activity size={13} className="text-blue-600"/><span className="text-[9px] font-bold text-slate-700">Dispute-round progress</span><div className="ml-auto flex gap-1">{[1,2,3,4,5].map((x)=><span key={x} className={`h-1.5 w-8 rounded-full ${x<4?'bg-blue-600':'bg-slate-200'}`}/>)}</div><span className="text-[9px] font-black text-blue-600">3/5</span></div>
        </div>
      </div>
    </div>
    {!compact && <><div className="absolute -right-4 top-[30%] hidden rounded-xl border border-slate-200 bg-white p-3 shadow-xl sm:block"><div className="flex items-center gap-2"><span className="grid h-7 w-7 place-items-center rounded-lg bg-amber-50 text-amber-600"><CircleAlert size={14}/></span><div><p className="text-[9px] font-black text-slate-800">Deadline approaching</p><p className="text-[8px] text-slate-500">Experian · 4 days</p></div></div></div><div className="absolute -bottom-5 left-8 hidden rounded-xl border border-slate-200 bg-white p-3 shadow-xl sm:block"><div className="flex items-center gap-2"><span className="grid h-7 w-7 place-items-center rounded-lg bg-emerald-50 text-emerald-600"><Check size={14}/></span><div><p className="text-[9px] font-black text-slate-800">Draft ready for review</p><p className="text-[8px] text-slate-500">Human approval required</p></div></div></div></>}
  </div>;
}
