'use client';
import React, { useState, useMemo, useEffect, useCallback } from 'react';
import { Search, Filter, Plus, Eye, FileText, AlertTriangle, CheckCircle2, Clock, ChevronUp, ChevronDown, X, RefreshCw, ArrowRight, Shield, Zap } from 'lucide-react';
import StatusBadge from '@/components/ui/StatusBadge';
import EmptyState from '@/components/ui/EmptyState';
import Modal from '@/components/ui/Modal';
import { toast } from 'sonner';
import { createClient } from '@/lib/supabase/client';
import Link from 'next/link';

type DisputeStatus = 'pending' | 'in_progress' | 'sent' | 'awaiting' | 'resolved' | 'rejected';
type DisputePriority = 'high' | 'medium' | 'low';

interface ClientDispute {
  id: string;
  clientId: string;
  clientName: string;
  creditorName: string;
  accountNumber: string;
  negativeItemType: string;
  bureau: string;
  disputeReason: string;
  disputeLetterTemplate: string;
  amount: number | null;
  dateReported: string;
  priority: DisputePriority;
  disputeStatus: DisputeStatus;
  responseDueDate: string;
  daysRemaining: number;
  autoGenerated: boolean;
  letterId: string | null;
  createdAt: string;
}

const bureauConfig: Record<string, { className: string }> = {
  Equifax: { className: 'bureau-eq' },
  Experian: { className: 'bureau-ex' },
  TransUnion: { className: 'bureau-tu' },
};

const priorityConfig: Record<DisputePriority, { label: string; className: string }> = {
  high: { label: 'High', className: 'bg-danger/10 text-danger border-danger/20' },
  medium: { label: 'Medium', className: 'bg-warning/10 text-warning border-warning/20' },
  low: { label: 'Low', className: 'bg-muted text-muted-foreground border-border' },
};

const itemTypeLabels: Record<string, string> = {
  collection: 'Collection',
  charge_off: 'Charge-Off',
  late_payment: 'Late Payment',
  repossession: 'Repossession',
  bankruptcy: 'Bankruptcy',
  hard_inquiry: 'Hard Inquiry',
  other: 'Other',
};

type SortField = 'clientName' | 'creditorName' | 'bureau' | 'priority' | 'daysRemaining' | 'createdAt';

function mapRow(row: any, clientMap: Record<string, string>): ClientDispute {
  const statusMap: Record<string, DisputeStatus> = {
    draft: 'pending', ready: 'pending', generated: 'in_progress', sent: 'sent',
    waiting_for_response: 'awaiting', escalated: 'in_progress', updated: 'resolved',
    deleted: 'resolved', verified: 'resolved', closed: 'resolved',
  };
  return {
    id: row.id,
    clientId: row.client_id ?? '',
    clientName: clientMap[row.client_id] ?? row.client_name ?? 'Unknown Client',
    creditorName: row.creditor_name ?? '',
    accountNumber: row.account_number_masked ?? '',
    negativeItemType: row.negative_category ?? 'other',
    bureau: row.bureau ?? 'Unknown',
    disputeReason: row.dispute_reason ?? '',
    disputeLetterTemplate: row.dispute_letter_template ?? 'FCRA Section 611',
    amount: row.balance ?? null,
    dateReported: row.date_reported
      ? new Date(row.date_reported).toLocaleDateString('en-US', { month: '2-digit', day: '2-digit', year: 'numeric' })
      : '',
    priority: (row.is_collection || row.negative_category === 'charge_off' ? 'high' : 'medium') as DisputePriority,
    disputeStatus: statusMap[row.dispute_status] ?? 'pending',
    responseDueDate: row.response_due_date
      ? new Date(row.response_due_date).toLocaleDateString('en-US', { month: '2-digit', day: '2-digit', year: 'numeric' })
      : '',
    daysRemaining: row.days_remaining ?? 30,
    autoGenerated: Boolean(row.report_id),
    letterId: row.letter_id ?? null,
    createdAt: row.created_at ?? '',
  };
}

interface DisputeDetailModal {
  dispute: ClientDispute;
  onClose: () => void;
  onGenerateLetter: (dispute: ClientDispute) => void;
  onStatusChange: (id: string, status: DisputeStatus) => void;
}

function DisputeDetailModal({ dispute, onClose, onGenerateLetter, onStatusChange }: DisputeDetailModal) {
  return (
    <div className="space-y-5">
      {/* Header info */}
      <div className="grid grid-cols-2 gap-4">
        <div className="space-y-1">
          <p className="text-xs font-medium text-muted-foreground uppercase tracking-wide">Client</p>
          <p className="text-sm font-semibold text-foreground">{dispute.clientName}</p>
        </div>
        <div className="space-y-1">
          <p className="text-xs font-medium text-muted-foreground uppercase tracking-wide">Bureau</p>
          <span className={`badge ${bureauConfig[dispute.bureau]?.className ?? 'bg-muted text-muted-foreground border-border'}`}>{dispute.bureau}</span>
        </div>
        <div className="space-y-1">
          <p className="text-xs font-medium text-muted-foreground uppercase tracking-wide">Creditor</p>
          <p className="text-sm font-semibold text-foreground">{dispute.creditorName}</p>
        </div>
        <div className="space-y-1">
          <p className="text-xs font-medium text-muted-foreground uppercase tracking-wide">Item Type</p>
          <p className="text-sm text-foreground">{itemTypeLabels[dispute.negativeItemType] ?? dispute.negativeItemType}</p>
        </div>
        {dispute.accountNumber && (
          <div className="space-y-1">
            <p className="text-xs font-medium text-muted-foreground uppercase tracking-wide">Account #</p>
            <p className="text-sm font-mono text-foreground">****{dispute.accountNumber}</p>
          </div>
        )}
        {dispute.amount && (
          <div className="space-y-1">
            <p className="text-xs font-medium text-muted-foreground uppercase tracking-wide">Amount</p>
            <p className="text-sm font-semibold text-foreground">${dispute.amount.toLocaleString()}</p>
          </div>
        )}
        {dispute.dateReported && (
          <div className="space-y-1">
            <p className="text-xs font-medium text-muted-foreground uppercase tracking-wide">Date Reported</p>
            <p className="text-sm text-foreground">{dispute.dateReported}</p>
          </div>
        )}
        <div className="space-y-1">
          <p className="text-xs font-medium text-muted-foreground uppercase tracking-wide">Response Due</p>
          <p className="text-sm text-foreground">{dispute.responseDueDate}</p>
        </div>
      </div>

      {/* Dispute reason */}
      <div className="p-3 bg-muted/40 rounded-xl border border-border">
        <p className="text-xs font-medium text-muted-foreground uppercase tracking-wide mb-1.5">Dispute Reason</p>
        <p className="text-sm text-foreground leading-relaxed">{dispute.disputeReason}</p>
      </div>

      {/* Template */}
      <div className="flex items-center gap-2 p-3 bg-primary/5 rounded-xl border border-primary/20">
        <FileText size={15} className="text-primary shrink-0" />
        <div>
          <p className="text-xs font-medium text-muted-foreground">Recommended Template</p>
          <p className="text-sm font-semibold text-foreground">{dispute.disputeLetterTemplate}</p>
        </div>
      </div>

      {/* Status update */}
      <div>
        <p className="text-xs font-medium text-muted-foreground uppercase tracking-wide mb-2">Update Status</p>
        <div className="flex flex-wrap gap-2">
          {(['pending', 'in_progress', 'sent', 'awaiting', 'resolved', 'rejected'] as DisputeStatus[]).map(s => (
            <button
              key={`status-btn-${s}`}
              onClick={() => onStatusChange(dispute.id, s)}
              className={`px-3 py-1.5 rounded-lg text-xs font-medium border transition-colors ${
                dispute.disputeStatus === s
                  ? 'bg-primary text-primary-foreground border-primary'
                  : 'bg-card text-muted-foreground border-border hover:bg-muted'
              }`}
            >
              {s.charAt(0).toUpperCase() + s.slice(1).replace('_', ' ')}
            </button>
          ))}
        </div>
      </div>

      {/* Actions */}
      <div className="flex justify-end gap-2 pt-2 border-t border-border">
        <button onClick={onClose} className="btn-secondary">Close</button>
        <button
          onClick={() => { onGenerateLetter(dispute); onClose(); }}
          className="btn-primary flex items-center gap-2"
        >
          <FileText size={14} />
          Generate Letter
        </button>
      </div>
    </div>
  );
}

export default function DisputesContent() {
  const [disputes, setDisputes] = useState<ClientDispute[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  const [search, setSearch] = useState('');
  const [bureauFilter, setBureauFilter] = useState('All Bureaus');
  const [statusFilter, setStatusFilter] = useState('All Statuses');
  const [priorityFilter, setPriorityFilter] = useState('All Priorities');
  const [typeFilter, setTypeFilter] = useState('All Types');
  const [showFilters, setShowFilters] = useState(false);
  const [sortField, setSortField] = useState<SortField>('daysRemaining');
  const [sortDir, setSortDir] = useState<'asc' | 'desc'>('asc');
  const [selectedRows, setSelectedRows] = useState<Set<string>>(new Set());
  const [currentPage, setCurrentPage] = useState(1);
  const [detailDispute, setDetailDispute] = useState<ClientDispute | null>(null);
  const perPage = 15;

  const supabase = createClient();

  const fetchDisputes = useCallback(async () => {
    setLoading(true);
    setError(null);
    try {
      const { data: { user } } = await supabase.auth.getUser();
      if (!user) { setLoading(false); return; }

      // Fetch client names for mapping
      const { data: clients } = await supabase
        .from('staff_clients')
        .select('id, name')
        .eq('owner_id', user.id);

      const clientMap: Record<string, string> = {};
      (clients ?? []).forEach((c: any) => { clientMap[c.id] = c.name; });

      const { data, error: fetchError } = await supabase
        .from('negative_items')
        .select('*')
        .eq('owner_id', user.id)
        .or('tag_status.eq.dispute,is_selected.eq.true')
        .order('created_at', { ascending: false });

      if (fetchError) {
        if (fetchError.code?.startsWith('42')) throw fetchError;
        setError(fetchError.message);
        return;
      }
      setDisputes((data ?? []).map((row: any) => mapRow(row, clientMap)));
    } catch (err: any) {
      setError(err?.message ?? 'Failed to load disputes');
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => { fetchDisputes(); }, [fetchDisputes]);

  const handleStatusChange = async (id: string, status: DisputeStatus) => {
    try {
      const workflowStatus: Record<DisputeStatus, string> = {
        pending: 'ready', in_progress: 'generated', sent: 'sent',
        awaiting: 'waiting_for_response', resolved: 'closed', rejected: 'closed',
      };
      const { error: updError } = await supabase
        .from('negative_items')
        .update({ dispute_status: workflowStatus[status] })
        .eq('id', id)
        .eq('owner_id', (await supabase.auth.getUser()).data.user?.id);
      if (updError) throw updError;
      setDisputes(prev => prev.map(d => d.id === id ? { ...d, disputeStatus: status } : d));
      // Update detail modal if open
      setDetailDispute(prev => prev?.id === id ? { ...prev, disputeStatus: status } : prev);
      toast.success(`Dispute status updated to ${status}`);
    } catch (err: any) {
      toast.error('Failed to update status');
    }
  };

  const handleGenerateLetter = (dispute: ClientDispute) => {
    // Navigate to dispute letters with pre-filled context
    const params = new URLSearchParams({
      clientId: dispute.clientId,
      bureau: dispute.bureau,
      template: dispute.disputeLetterTemplate,
      disputeId: dispute.id,
    });
    window.location.href = `/dispute-letter-management?${params.toString()}`;
  };

  const handleBulkGenerateLetters = async () => {
    const selected = disputes.filter(d => selectedRows.has(d.id));
    if (selected.length === 0) return;
    toast.success(`Navigating to generate ${selected.length} dispute letter${selected.length !== 1 ? 's' : ''}…`);
    setTimeout(() => {
      window.location.href = '/dispute-letter-management';
    }, 800);
  };

  const filtered = useMemo(() => {
    let data = [...disputes];
    if (search) {
      const q = search.toLowerCase();
      data = data.filter(d =>
        d.clientName.toLowerCase().includes(q) ||
        d.creditorName.toLowerCase().includes(q) ||
        d.bureau.toLowerCase().includes(q) ||
        d.negativeItemType.toLowerCase().includes(q)
      );
    }
    if (bureauFilter !== 'All Bureaus') data = data.filter(d => d.bureau === bureauFilter);
    if (statusFilter !== 'All Statuses') data = data.filter(d => d.disputeStatus === statusFilter);
    if (priorityFilter !== 'All Priorities') data = data.filter(d => d.priority === priorityFilter);
    if (typeFilter !== 'All Types') data = data.filter(d => d.negativeItemType === typeFilter);
    data.sort((a, b) => {
      const av = a[sortField] as string | number;
      const bv = b[sortField] as string | number;
      return sortDir === 'asc' ? (av > bv ? 1 : -1) : (av < bv ? 1 : -1);
    });
    return data;
  }, [disputes, search, bureauFilter, statusFilter, priorityFilter, typeFilter, sortField, sortDir]);

  const paginated = filtered.slice((currentPage - 1) * perPage, currentPage * perPage);
  const totalPages = Math.ceil(filtered.length / perPage);

  const toggleSort = (field: SortField) => {
    if (sortField === field) setSortDir(d => d === 'asc' ? 'desc' : 'asc');
    else { setSortField(field); setSortDir('asc'); }
  };

  const toggleRow = (id: string) => {
    setSelectedRows(prev => {
      const next = new Set(prev);
      next.has(id) ? next.delete(id) : next.add(id);
      return next;
    });
  };

  const toggleAll = () => {
    if (selectedRows.size === paginated.length) setSelectedRows(new Set());
    else setSelectedRows(new Set(paginated.map(d => d.id)));
  };

  const SortIcon = ({ field }: { field: SortField }) => (
    <span className="ml-1 inline-flex flex-col">
      <ChevronUp size={10} className={sortField === field && sortDir === 'asc' ? 'text-primary' : 'text-muted-foreground/40'} />
      <ChevronDown size={10} className={sortField === field && sortDir === 'desc' ? 'text-primary' : 'text-muted-foreground/40'} />
    </span>
  );

  const getDaysLabel = (days: number, status: DisputeStatus) => {
    if (status === 'resolved') return { label: 'Resolved', className: 'bg-success/10 text-success border-success/20' };
    if (status === 'rejected') return { label: 'Rejected', className: 'bg-muted text-muted-foreground border-border' };
    if (days < 0) return { label: `${Math.abs(days)}d overdue`, className: 'bg-danger/10 text-danger border-danger/20' };
    if (days <= 5) return { label: `${days}d left`, className: 'bg-danger/10 text-danger border-danger/20' };
    if (days <= 10) return { label: `${days}d left`, className: 'bg-warning/10 text-warning border-warning/20' };
    return { label: `${days}d left`, className: 'bg-muted text-muted-foreground border-border' };
  };

  const stats = [
    { label: 'Total Disputes', value: disputes.length, icon: Shield, bg: 'bg-primary/10', color: 'text-primary' },
    { label: 'Pending Action', value: disputes.filter(d => d.disputeStatus === 'pending').length, icon: Clock, bg: 'bg-warning/10', color: 'text-warning' },
    { label: 'High Priority', value: disputes.filter(d => d.priority === 'high').length, icon: AlertTriangle, bg: 'bg-danger/10', color: 'text-danger' },
    { label: 'Resolved', value: disputes.filter(d => d.disputeStatus === 'resolved').length, icon: CheckCircle2, bg: 'bg-success/10', color: 'text-success' },
  ];

  if (loading) {
    return (
      <div className="app-page page-stack">
        <div className="flex items-center justify-between">
          <div>
            <h1 className="page-title">Disputes</h1>
            <p className="page-description">Loading disputes…</p>
          </div>
        </div>
        <div className="card p-8 flex items-center justify-center">
          <div className="flex flex-col items-center gap-3">
            <div className="w-8 h-8 border-2 border-primary border-t-transparent rounded-full animate-spin" />
            <p className="text-sm text-muted-foreground">Loading dispute records…</p>
          </div>
        </div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="app-page">
        <div className="card p-8 flex flex-col items-center gap-3 text-center">
          <AlertTriangle size={32} className="text-danger" />
          <p className="text-sm font-semibold text-foreground">Failed to load disputes</p>
          <p className="text-xs text-muted-foreground">{error}</p>
          <button onClick={fetchDisputes} className="btn-primary mt-2 flex items-center gap-2">
            <RefreshCw size={14} /> Retry
          </button>
        </div>
      </div>
    );
  }

  return (
    <div className="app-page page-stack">
      {/* Header */}
      <div className="page-header">
        <div>
          <h1 className="page-title">Disputes</h1>
          <p className="page-description">
            {filtered.length} dispute{filtered.length !== 1 ? 's' : ''} · auto-generated from credit report analysis
          </p>
        </div>
        <div className="page-actions">
          <button onClick={fetchDisputes} className="btn-secondary flex items-center gap-1.5">
            <RefreshCw size={14} /> Refresh
          </button>
          <Link href="/dispute-letter-management" className="btn-primary flex items-center gap-1.5">
            <FileText size={15} /> Generate Letters
          </Link>
        </div>
      </div>

      {/* Empty state — no disputes yet */}
      {disputes.length === 0 && (
        <div className="card p-10 flex flex-col items-center gap-4 text-center">
          <div className="w-14 h-14 rounded-2xl bg-primary/10 flex items-center justify-center">
            <Zap size={24} className="text-primary" />
          </div>
          <div>
            <h3 className="text-base font-semibold text-foreground">No disputes yet</h3>
            <p className="text-sm text-muted-foreground mt-1 max-w-sm">
              Disputes are auto-created when you add a client and analyze their credit report. Upload a report to get started.
            </p>
          </div>
          <div className="flex items-center gap-3">
            <Link href="/client-management" className="btn-primary flex items-center gap-2">
              <Plus size={14} /> Add Client &amp; Upload Report
            </Link>
          </div>
          <div className="flex items-center gap-6 mt-2 text-xs text-muted-foreground">
            {['Upload Report', 'AI Parses Items', 'Disputes Created', 'Generate Letters'].map((step, i) => (
              <React.Fragment key={`step-${i}`}>
                <span className="flex items-center gap-1.5">
                  <span className="w-5 h-5 rounded-full bg-primary/10 text-primary text-xs font-bold flex items-center justify-center">{i + 1}</span>
                  {step}
                </span>
                {i < 3 && <ArrowRight size={12} className="text-muted-foreground/40" />}
              </React.Fragment>
            ))}
          </div>
        </div>
      )}

      {disputes.length > 0 && (
        <>
          {/* Stats */}
          <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
            {stats.map(s => {
              const StatIcon = s.icon;
              return (
                <div key={`dstat-${s.label}`} className="card p-4 flex items-center gap-3">
                  <div className={`w-9 h-9 rounded-lg ${s.bg} flex items-center justify-center shrink-0`}>
                    <StatIcon size={17} className={s.color} />
                  </div>
                  <div>
                    <p className="text-lg font-bold text-foreground tabular-nums">{s.value}</p>
                    <p className="text-xs text-muted-foreground">{s.label}</p>
                  </div>
                </div>
              );
            })}
          </div>

          {/* Search + Filters */}
          <div className="card p-4 space-y-3">
            <div className="flex items-center gap-3">
              <div className="relative flex-1">
                <Search size={15} className="absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground" />
                <input
                  type="text"
                  placeholder="Search by client, creditor, or bureau…"
                  value={search}
                  onChange={e => { setSearch(e.target.value); setCurrentPage(1); }}
                  className="input-field pl-9"
                />
              </div>
              {/* Priority quick filters */}
              <div className="flex items-center gap-1.5">
                {['All Priorities', 'high', 'medium', 'low'].map(p => (
                  <button
                    key={`pf-${p}`}
                    onClick={() => { setPriorityFilter(p); setCurrentPage(1); }}
                    className={`px-3 py-1.5 rounded-lg text-xs font-medium transition-colors border ${
                      priorityFilter === p
                        ? p === 'high' ? 'bg-danger/10 text-danger border-danger/30'
                          : p === 'medium' ? 'bg-warning/10 text-warning border-warning/30'
                          : p === 'low' ? 'bg-muted text-muted-foreground border-border'
                          : 'bg-primary/10 text-primary border-primary/30' :'bg-card text-muted-foreground border-border hover:bg-muted'
                    }`}
                  >
                    {p === 'All Priorities' ? 'All' : p.charAt(0).toUpperCase() + p.slice(1)}
                  </button>
                ))}
              </div>
              <button
                onClick={() => setShowFilters(!showFilters)}
                className={`btn-secondary flex items-center gap-1.5 ${showFilters ? 'bg-primary/10 text-primary' : ''}`}
              >
                <Filter size={15} /> Filters
              </button>
            </div>
            {showFilters && (
              <div className="flex flex-wrap items-end gap-3 pt-2 border-t border-border fade-in">
                <div>
                  <label className="text-xs font-medium text-muted-foreground mb-1 block">Bureau</label>
                  <select value={bureauFilter} onChange={e => { setBureauFilter(e.target.value); setCurrentPage(1); }} className="input-field text-xs py-1.5 w-36">
                    {['All Bureaus', 'Equifax', 'Experian', 'TransUnion'].map(o => <option key={`bf-${o}`} value={o}>{o}</option>)}
                  </select>
                </div>
                <div>
                  <label className="text-xs font-medium text-muted-foreground mb-1 block">Status</label>
                  <select value={statusFilter} onChange={e => { setStatusFilter(e.target.value); setCurrentPage(1); }} className="input-field text-xs py-1.5 w-40">
                    {['All Statuses', 'pending', 'in_progress', 'sent', 'awaiting', 'resolved', 'rejected'].map(o => (
                      <option key={`sf-${o}`} value={o}>{o.charAt(0).toUpperCase() + o.slice(1).replace('_', ' ')}</option>
                    ))}
                  </select>
                </div>
                <div>
                  <label className="text-xs font-medium text-muted-foreground mb-1 block">Item Type</label>
                  <select value={typeFilter} onChange={e => { setTypeFilter(e.target.value); setCurrentPage(1); }} className="input-field text-xs py-1.5 w-40">
                    <option value="All Types">All Types</option>
                    {Object.entries(itemTypeLabels).map(([k, v]) => <option key={`tf-${k}`} value={k}>{v}</option>)}
                  </select>
                </div>
                <button
                  onClick={() => { setBureauFilter('All Bureaus'); setStatusFilter('All Statuses'); setPriorityFilter('All Priorities'); setTypeFilter('All Types'); }}
                  className="btn-ghost flex items-center gap-1 text-xs"
                >
                  <X size={12} /> Clear
                </button>
              </div>
            )}
          </div>

          {/* Bulk action bar */}
          {selectedRows.size > 0 && (
            <div className="fixed bottom-6 left-1/2 -translate-x-1/2 z-40 flex items-center gap-3 bg-foreground text-background rounded-xl px-5 py-3 shadow-xl slide-up">
              <span className="text-sm font-semibold">{selectedRows.size} selected</span>
              <div className="w-px h-4 bg-white/20" />
              <button className="text-sm font-medium hover:text-white/80 transition-colors" onClick={handleBulkGenerateLetters}>
                Generate Letters
              </button>
              <button
                className="text-sm font-medium hover:text-white/80 transition-colors"
                onClick={async () => {
                  for (const id of selectedRows) {
                    await handleStatusChange(id, 'in_progress');
                  }
                  setSelectedRows(new Set());
                }}
              >
                Mark In Progress
              </button>
              <button onClick={() => setSelectedRows(new Set())} className="ml-2 p-1 hover:bg-white/10 rounded transition-colors">
                <X size={14} />
              </button>
            </div>
          )}

          {/* Table */}
          <div className="card overflow-hidden">
            <div className="overflow-x-auto">
              <table className="w-full min-w-[1100px]">
                <thead className="bg-muted/50 border-b border-border">
                  <tr>
                    <th className="table-header w-10">
                      <input type="checkbox" checked={selectedRows.size === paginated.length && paginated.length > 0} onChange={toggleAll} className="w-4 h-4 rounded border-input accent-primary" aria-label="Select all" />
                    </th>
                    <th className="table-header cursor-pointer select-none" onClick={() => toggleSort('clientName')}>
                      <span className="flex items-center">Client <SortIcon field="clientName" /></span>
                    </th>
                    <th className="table-header cursor-pointer select-none" onClick={() => toggleSort('creditorName')}>
                      <span className="flex items-center">Creditor <SortIcon field="creditorName" /></span>
                    </th>
                    <th className="table-header">Item Type</th>
                    <th className="table-header cursor-pointer select-none" onClick={() => toggleSort('bureau')}>
                      <span className="flex items-center">Bureau <SortIcon field="bureau" /></span>
                    </th>
                    <th className="table-header cursor-pointer select-none" onClick={() => toggleSort('priority')}>
                      <span className="flex items-center">Priority <SortIcon field="priority" /></span>
                    </th>
                    <th className="table-header">Status</th>
                    <th className="table-header cursor-pointer select-none" onClick={() => toggleSort('daysRemaining')}>
                      <span className="flex items-center">Due Date <SortIcon field="daysRemaining" /></span>
                    </th>
                    <th className="table-header">Template</th>
                    <th className="table-header w-28">Actions</th>
                  </tr>
                </thead>
                <tbody>
                  {paginated.length === 0 ? (
                    <tr>
                      <td colSpan={10}>
                        <EmptyState
                          icon={Shield}
                          title="No disputes match your filters"
                          description="Try adjusting your search or filter criteria."
                          action={{ label: 'Clear Filters', onClick: () => { setSearch(''); setBureauFilter('All Bureaus'); setStatusFilter('All Statuses'); setPriorityFilter('All Priorities'); setTypeFilter('All Types'); } }}
                        />
                      </td>
                    </tr>
                  ) : (
                    paginated.map(dispute => {
                      const bc = bureauConfig[dispute.bureau] ?? { className: 'bg-muted text-muted-foreground border-border' };
                      const pc = priorityConfig[dispute.priority];
                      const dl = getDaysLabel(dispute.daysRemaining, dispute.disputeStatus);
                      return (
                        <tr key={dispute.id} className={`border-b border-border row-hover ${selectedRows.has(dispute.id) ? 'bg-primary/5' : ''}`}>
                          <td className="table-cell">
                            <input type="checkbox" checked={selectedRows.has(dispute.id)} onChange={() => toggleRow(dispute.id)} className="w-4 h-4 rounded border-input accent-primary" aria-label={`Select ${dispute.creditorName}`} />
                          </td>
                          <td className="table-cell">
                            <div>
                              <p className="font-semibold text-sm text-foreground">{dispute.clientName}</p>
                              {dispute.autoGenerated && (
                                <span className="inline-flex items-center gap-1 text-2xs text-primary bg-primary/10 px-1.5 py-0.5 rounded mt-0.5">
                                  <Zap size={9} /> Auto
                                </span>
                              )}
                            </div>
                          </td>
                          <td className="table-cell">
                            <div>
                              <p className="text-sm font-medium text-foreground">{dispute.creditorName}</p>
                              {dispute.accountNumber && (
                                <p className="text-xs text-muted-foreground font-mono">****{dispute.accountNumber}</p>
                              )}
                              {dispute.amount && (
                                <p className="text-xs text-muted-foreground">${dispute.amount.toLocaleString()}</p>
                              )}
                            </div>
                          </td>
                          <td className="table-cell">
                            <span className="text-xs text-muted-foreground bg-muted px-2 py-1 rounded">
                              {itemTypeLabels[dispute.negativeItemType] ?? dispute.negativeItemType}
                            </span>
                          </td>
                          <td className="table-cell">
                            <span className={`badge ${bc.className}`}>{dispute.bureau}</span>
                          </td>
                          <td className="table-cell">
                            <span className={`badge ${pc.className}`}>{pc.label}</span>
                          </td>
                          <td className="table-cell">
                            <StatusBadge status={dispute.disputeStatus} />
                          </td>
                          <td className="table-cell">
                            <div>
                              <p className="text-xs text-muted-foreground mb-1">{dispute.responseDueDate}</p>
                              <span className={`badge ${dl.className}`}>
                                {dispute.daysRemaining < 0 && dispute.disputeStatus !== 'resolved' && dispute.disputeStatus !== 'rejected'
                                  ? <AlertTriangle size={10} className="mr-1" />
                                  : <Clock size={10} className="mr-1" />}
                                {dl.label}
                              </span>
                            </div>
                          </td>
                          <td className="table-cell">
                            <p className="text-xs text-muted-foreground truncate max-w-[120px]" title={dispute.disputeLetterTemplate}>
                              {dispute.disputeLetterTemplate}
                            </p>
                          </td>
                          <td className="table-cell">
                            <div className="flex items-center gap-1">
                              <button
                                onClick={() => setDetailDispute(dispute)}
                                className="p-1.5 hover:bg-muted rounded-lg transition-colors"
                                title="View dispute details"
                              >
                                <Eye size={14} className="text-muted-foreground" />
                              </button>
                              <button
                                onClick={() => handleGenerateLetter(dispute)}
                                className="p-1.5 hover:bg-primary/10 rounded-lg transition-colors"
                                title="Generate dispute letter"
                              >
                                <FileText size={14} className="text-primary" />
                              </button>
                              <button
                                onClick={() => handleStatusChange(dispute.id, dispute.disputeStatus === 'resolved' ? 'pending' : 'resolved')}
                                className="p-1.5 hover:bg-success/10 rounded-lg transition-colors"
                                title={dispute.disputeStatus === 'resolved' ? 'Reopen dispute' : 'Mark resolved'}
                              >
                                <CheckCircle2 size={14} className={dispute.disputeStatus === 'resolved' ? 'text-success' : 'text-muted-foreground'} />
                              </button>
                            </div>
                          </td>
                        </tr>
                      );
                    })
                  )}
                </tbody>
              </table>
            </div>

            {/* Pagination */}
            {filtered.length > 0 && (
              <div className="flex items-center justify-between px-4 py-3 border-t border-border">
                <p className="text-xs text-muted-foreground">
                  Showing {(currentPage - 1) * perPage + 1}–{Math.min(currentPage * perPage, filtered.length)} of {filtered.length} disputes
                </p>
                <div className="flex items-center gap-1">
                  <button onClick={() => setCurrentPage(p => Math.max(1, p - 1))} disabled={currentPage === 1} className="btn-ghost px-2 py-1 text-xs disabled:opacity-40">Previous</button>
                  {Array.from({ length: Math.min(totalPages, 7) }).map((_, i) => (
                    <button key={`dpage-${i + 1}`} onClick={() => setCurrentPage(i + 1)} className={`w-7 h-7 rounded-lg text-xs font-medium transition-colors ${currentPage === i + 1 ? 'bg-primary text-primary-foreground' : 'hover:bg-muted text-muted-foreground'}`}>{i + 1}</button>
                  ))}
                  <button onClick={() => setCurrentPage(p => Math.min(totalPages, p + 1))} disabled={currentPage === totalPages} className="btn-ghost px-2 py-1 text-xs disabled:opacity-40">Next</button>
                </div>
              </div>
            )}
          </div>
        </>
      )}

      {/* Dispute Detail Modal */}
      {detailDispute && (
        <Modal
          open={!!detailDispute}
          onClose={() => setDetailDispute(null)}
          title={`Dispute — ${detailDispute.creditorName}`}
          subtitle={`${detailDispute.clientName} · ${detailDispute.bureau}`}
          size="lg"
        >
          <DisputeDetailModal
            dispute={detailDispute}
            onClose={() => setDetailDispute(null)}
            onGenerateLetter={handleGenerateLetter}
            onStatusChange={handleStatusChange}
          />
        </Modal>
      )}
    </div>
  );
}
